CREATE TRIGGER trg_notify_capital_transfer AFTER INSERT ON public.capital_transfers FOR EACH ROW EXECUTE FUNCTION notify_on_capital_transfer();
CREATE TRIGGER trg_cash_custody_updated_at BEFORE UPDATE ON public.cash_custody_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_cash_custody AFTER INSERT ON public.cash_custody_requests FOR EACH ROW EXECUTE FUNCTION notify_cash_custody_request();
CREATE TRIGGER trg_chat_deliver_receipts AFTER INSERT ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION fn_chat_deliver_receipts();
CREATE TRIGGER trg_chat_messages_updated_at BEFORE UPDATE ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_chat_notify_new_message AFTER INSERT ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION fn_chat_notify_new_message();
CREATE TRIGGER trg_chat_presence_updated_at BEFORE UPDATE ON public.chat_presence FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_chat_room_members_updated_at BEFORE UPDATE ON public.chat_room_members FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_chat_room_policies_updated_at BEFORE UPDATE ON public.chat_room_policies FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_chat_rooms_updated_at BEFORE UPDATE ON public.chat_rooms FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_chat_typing_state_updated_at BEFORE UPDATE ON public.chat_typing_state FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER update_conversation_settings_updated_at BEFORE UPDATE ON public.conversation_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_merchant_on_customer_connection AFTER INSERT ON public.customer_merchant_connections FOR EACH ROW EXECUTE FUNCTION notify_merchant_on_customer_connection();
CREATE TRIGGER update_cmc_updated_at BEFORE UPDATE ON public.customer_merchant_connections FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_customer_message AFTER INSERT ON public.customer_messages FOR EACH ROW EXECUTE FUNCTION fn_notify_customer_message();
CREATE TRIGGER trg_notify_on_customer_message AFTER INSERT ON public.customer_messages FOR EACH ROW EXECUTE FUNCTION notify_on_customer_message();
CREATE TRIGGER trg_notify_customer_on_order_update AFTER UPDATE ON public.customer_orders FOR EACH ROW EXECUTE FUNCTION notify_customer_on_order_update();
CREATE TRIGGER trg_notify_customer_order AFTER INSERT ON public.customer_orders FOR EACH ROW EXECUTE FUNCTION notify_customer_order_created();
CREATE TRIGGER trg_notify_merchant_on_customer_order AFTER INSERT ON public.customer_orders FOR EACH ROW EXECUTE FUNCTION notify_merchant_on_customer_order();
CREATE TRIGGER update_customer_orders_updated_at BEFORE UPDATE ON public.customer_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_customer_profiles_updated_at BEFORE UPDATE ON public.customer_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_capital_ledger AFTER INSERT ON public.deal_capital_ledger FOR EACH ROW EXECUTE FUNCTION notify_capital_ledger_change();
CREATE TRIGGER trg_validate_capital_ledger_type BEFORE INSERT OR UPDATE ON public.deal_capital_ledger FOR EACH ROW EXECUTE FUNCTION validate_capital_ledger_type();
CREATE TRIGGER update_merchant_approvals_updated_at BEFORE UPDATE ON public.merchant_approvals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_merchant_deal AFTER INSERT OR UPDATE ON public.merchant_deals FOR EACH ROW EXECUTE FUNCTION notify_merchant_deal_change();
CREATE TRIGGER update_merchant_deals_updated_at BEFORE UPDATE ON public.merchant_deals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER on_invite_status_change_notification AFTER UPDATE ON public.merchant_invites FOR EACH ROW EXECUTE FUNCTION notify_on_invite_status_change();
CREATE TRIGGER on_new_invite_notification AFTER INSERT ON public.merchant_invites FOR EACH ROW EXECUTE FUNCTION notify_on_new_invite();
CREATE TRIGGER update_merchant_liquidity_profiles_updated_at BEFORE UPDATE ON public.merchant_liquidity_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_on_new_message AFTER INSERT ON public.merchant_messages FOR EACH ROW EXECUTE FUNCTION notify_on_new_message();
CREATE TRIGGER trg_refresh_verification_tier BEFORE UPDATE ON public.merchant_profiles FOR EACH ROW EXECUTE FUNCTION fn_refresh_verification_tier();
CREATE TRIGGER trg_validate_discoverability BEFORE INSERT OR UPDATE ON public.merchant_profiles FOR EACH ROW EXECUTE FUNCTION validate_discoverability();
CREATE TRIGGER update_merchant_profiles_updated_at BEFORE UPDATE ON public.merchant_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_profit_record AFTER INSERT ON public.merchant_profits FOR EACH ROW EXECUTE FUNCTION notify_on_profit_record();
CREATE TRIGGER trg_validate_profit_status BEFORE INSERT OR UPDATE ON public.merchant_profits FOR EACH ROW EXECUTE FUNCTION validate_profit_status();
CREATE TRIGGER update_merchant_relationships_updated_at BEFORE UPDATE ON public.merchant_relationships FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_settlement AFTER INSERT ON public.merchant_settlements FOR EACH ROW EXECUTE FUNCTION notify_on_settlement();
CREATE TRIGGER trg_validate_settlement_status BEFORE INSERT OR UPDATE ON public.merchant_settlements FOR EACH ROW EXECUTE FUNCTION validate_settlement_status();
CREATE TRIGGER update_notification_prefs_updated_at BEFORE UPDATE ON public.notification_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_os_after_message_insert AFTER INSERT ON public.os_messages FOR EACH ROW EXECUTE FUNCTION os_after_message_insert();
CREATE TRIGGER trg_os_messages_notify AFTER INSERT ON public.os_messages FOR EACH ROW EXECUTE FUNCTION fn_os_messages_notify_counterparty();
CREATE TRIGGER trg_otc_dispute_notify AFTER INSERT ON public.otc_disputes FOR EACH ROW EXECUTE FUNCTION fn_notify_otc_dispute();
CREATE TRIGGER update_otc_disputes_updated_at BEFORE UPDATE ON public.otc_disputes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_otc_escrow_notify AFTER INSERT OR UPDATE ON public.otc_escrow FOR EACH ROW EXECUTE FUNCTION fn_notify_otc_escrow_deposit();
CREATE TRIGGER trg_sync_escrow_status AFTER INSERT OR UPDATE ON public.otc_escrow FOR EACH ROW EXECUTE FUNCTION fn_sync_escrow_status();
CREATE TRIGGER trg_otc_listings_updated_at BEFORE UPDATE ON public.otc_listings FOR EACH ROW EXECUTE FUNCTION update_otc_updated_at();
CREATE TRIGGER trg_refresh_otc_rating AFTER INSERT ON public.otc_reviews FOR EACH ROW EXECUTE FUNCTION fn_refresh_otc_rating();
CREATE TRIGGER trg_auto_pause_listing_on_complete AFTER UPDATE ON public.otc_trades FOR EACH ROW EXECUTE FUNCTION fn_auto_pause_listing_on_trade_complete();
CREATE TRIGGER trg_auto_release_escrow AFTER UPDATE ON public.otc_trades FOR EACH ROW EXECUTE FUNCTION fn_auto_release_escrow();
CREATE TRIGGER trg_notify_otc_trade AFTER INSERT OR UPDATE ON public.otc_trades FOR EACH ROW EXECUTE FUNCTION fn_notify_otc_trade();
CREATE TRIGGER trg_otc_trade_offer_notify AFTER INSERT ON public.otc_trades FOR EACH ROW EXECUTE FUNCTION fn_notify_otc_trade_offer();
CREATE TRIGGER trg_otc_trade_status_notify AFTER UPDATE ON public.otc_trades FOR EACH ROW EXECUTE FUNCTION fn_notify_otc_trade_status();
CREATE TRIGGER trg_otc_trades_updated_at BEFORE UPDATE ON public.otc_trades FOR EACH ROW EXECUTE FUNCTION update_otc_updated_at();
CREATE TRIGGER trg_refresh_otc_reputation AFTER UPDATE ON public.otc_trades FOR EACH ROW EXECUTE FUNCTION fn_refresh_otc_reputation();
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_auto_expire_agreements BEFORE INSERT OR UPDATE ON public.profit_share_agreements FOR EACH ROW EXECUTE FUNCTION auto_expire_agreements();
CREATE TRIGGER trg_notify_new_agreement AFTER INSERT ON public.profit_share_agreements FOR EACH ROW EXECUTE FUNCTION notify_on_new_agreement();
CREATE TRIGGER trg_validate_psa_ratios BEFORE INSERT OR UPDATE ON public.profit_share_agreements FOR EACH ROW EXECUTE FUNCTION validate_psa_ratios();
CREATE TRIGGER trg_validate_psa_settlement_way BEFORE INSERT OR UPDATE ON public.profit_share_agreements FOR EACH ROW EXECUTE FUNCTION validate_psa_settlement_way();
CREATE TRIGGER trg_validate_psa_status BEFORE INSERT OR UPDATE ON public.profit_share_agreements FOR EACH ROW EXECUTE FUNCTION validate_psa_status();
CREATE TRIGGER update_push_tokens_updated_at BEFORE UPDATE ON public.push_device_tokens FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_settlement_decisions_updated_at BEFORE UPDATE ON public.settlement_decisions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_validate_settlement_decision BEFORE INSERT OR UPDATE ON public.settlement_decisions FOR EACH ROW EXECUTE FUNCTION validate_settlement_decision();
CREATE TRIGGER trg_validate_settlement_period_cadence BEFORE INSERT OR UPDATE ON public.settlement_periods FOR EACH ROW EXECUTE FUNCTION validate_settlement_period_cadence();
CREATE TRIGGER trg_validate_settlement_period_resolution BEFORE INSERT OR UPDATE ON public.settlement_periods FOR EACH ROW EXECUTE FUNCTION validate_settlement_period_resolution();
CREATE TRIGGER trg_validate_settlement_period_status BEFORE INSERT OR UPDATE ON public.settlement_periods FOR EACH ROW EXECUTE FUNCTION validate_settlement_period_status();
CREATE TRIGGER update_settlement_periods_updated_at BEFORE UPDATE ON public.settlement_periods FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
