// ─── Demo Data for Development & Testing ────────────────────────────
// 3 AgreementTemplates, 5 MerchantAgreements, 10 Orders

import { createId, createMerchantAgreementSnapshot } from './utils';
import type { AgreementTemplate, MerchantAgreement, Order } from './types';

// ─── Agreement Templates ────────────────────────────────────────────

export const demoTemplates: AgreementTemplate[] = [
  {
    id: createId('TPL'),
    name: 'Standard Profit Share 20%',
    agreementType: 'profit_share',
    calculationMethod: 'profit_share',
    calculationConfig: { profitSharePercent: 20 },
    defaultCurrency: 'USDT',
    notes: 'Default profit sharing template at 20%',
    createdByUserId: 'demo-user-1',
    version: 1,
    isActive: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: createId('TPL'),
    name: 'Fixed Margin $2/unit',
    agreementType: 'fixed_margin',
    calculationMethod: 'fixed_margin',
    calculationConfig: { fixedMarginAmount: 2 },
    defaultCurrency: 'USDT',
    notes: 'Fixed margin of $2 per unit sold',
    createdByUserId: 'demo-user-1',
    version: 1,
    isActive: true,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
  {
    id: createId('TPL'),
    name: 'Spread 1.5%',
    agreementType: 'spread',
    calculationMethod: 'spread',
    calculationConfig: { spreadPercent: 1.5 },
    defaultCurrency: 'USDT',
    notes: 'Spread-based agreement at 1.5%',
    createdByUserId: 'demo-user-1',
    version: 1,
    isActive: true,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
];

// ─── Merchant Agreements ────────────────────────────────────────────

export const demoAgreements: MerchantAgreement[] = [
  {
    id: createId('AGR'),
    templateId: demoTemplates[0].id,
    merchantId: 'MRC-DEMO0001',
    merchantName: 'Al Jazeera Exchange',
    agreementType: 'profit_share',
    title: 'Profit Share — Al Jazeera Exchange',
    status: 'approved',
    approvedByUserId: 'demo-user-1',
    approvedAt: '2026-02-01T12:00:00Z',
    resolvedTermsSnapshot: createMerchantAgreementSnapshot(demoTemplates[0], '', 1),
    version: 1,
    isActive: true,
    createdAt: '2026-01-25T10:00:00Z',
    updatedAt: '2026-02-01T12:00:00Z',
  },
  {
    id: createId('AGR'),
    templateId: demoTemplates[1].id,
    merchantId: 'MRC-DEMO0002',
    merchantName: 'Gulf Star Trading',
    agreementType: 'fixed_margin',
    title: 'Fixed Margin — Gulf Star Trading',
    status: 'approved',
    approvedByUserId: 'demo-user-1',
    approvedAt: '2026-02-05T12:00:00Z',
    resolvedTermsSnapshot: createMerchantAgreementSnapshot(demoTemplates[1], '', 1),
    version: 1,
    isActive: true,
    createdAt: '2026-02-03T10:00:00Z',
    updatedAt: '2026-02-05T12:00:00Z',
  },
  {
    id: createId('AGR'),
    templateId: demoTemplates[0].id,
    merchantId: 'MRC-DEMO0003',
    merchantName: 'Desert Finance',
    agreementType: 'profit_share',
    title: 'Profit Share — Desert Finance',
    status: 'pending',
    approvedByUserId: null,
    approvedAt: null,
    resolvedTermsSnapshot: createMerchantAgreementSnapshot(demoTemplates[0], '', 1),
    version: 1,
    isActive: true,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: createId('AGR'),
    templateId: demoTemplates[2].id,
    merchantId: 'MRC-DEMO0001',
    merchantName: 'Al Jazeera Exchange',
    agreementType: 'spread',
    title: 'Spread — Al Jazeera Exchange',
    status: 'rejected',
    approvedByUserId: null,
    approvedAt: null,
    resolvedTermsSnapshot: createMerchantAgreementSnapshot(demoTemplates[2], '', 1),
    version: 1,
    isActive: false,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  },
  {
    id: createId('AGR'),
    templateId: demoTemplates[1].id,
    merchantId: 'MRC-DEMO0004',
    merchantName: 'Falcon Currency',
    agreementType: 'fixed_margin',
    title: 'Fixed Margin — Falcon Currency',
    status: 'archived',
    approvedByUserId: 'demo-user-1',
    approvedAt: '2026-01-20T12:00:00Z',
    resolvedTermsSnapshot: createMerchantAgreementSnapshot(demoTemplates[1], '', 1),
    version: 1,
    isActive: false,
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
  },
];

// ─── Orders ─────────────────────────────────────────────────────────

export const demoOrders: Order[] = [
  {
    id: createId('ORD'),
    direction: 'outgoing',
    merchantId: 'MRC-DEMO0001',
    merchantName: 'Al Jazeera Exchange',
    buyerId: 'BUY-001',
    buyerName: 'Ahmad Hassan',
    merchantAgreementId: demoAgreements[0].id,
    agreementTemplateId: demoTemplates[0].id,
    agreementType: 'profit_share',
    agreementSnapshot: { ...demoAgreements[0].resolvedTermsSnapshot },
    quantity: 100,
    unitPrice: 10,
    totalAmount: 1000,
    currency: 'USDT',
    computedNetProfit: 200,
    status: 'confirmed',
    createdByUserId: 'demo-user-1',
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'incoming',
    merchantId: 'MRC-DEMO0001',
    merchantName: 'Al Jazeera Exchange',
    buyerId: 'BUY-002',
    buyerName: 'Sara Ali',
    merchantAgreementId: demoAgreements[0].id,
    agreementTemplateId: demoTemplates[0].id,
    agreementType: 'profit_share',
    agreementSnapshot: { ...demoAgreements[0].resolvedTermsSnapshot },
    quantity: 50,
    unitPrice: 20,
    totalAmount: 1000,
    currency: 'USDT',
    computedNetProfit: 200,
    status: 'confirmed',
    createdByUserId: 'demo-user-2',
    createdAt: '2026-03-11T10:00:00Z',
    updatedAt: '2026-03-11T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'outgoing',
    merchantId: 'MRC-DEMO0002',
    merchantName: 'Gulf Star Trading',
    buyerId: 'BUY-003',
    buyerName: 'Omar Khalid',
    merchantAgreementId: demoAgreements[1].id,
    agreementTemplateId: demoTemplates[1].id,
    agreementType: 'fixed_margin',
    agreementSnapshot: { ...demoAgreements[1].resolvedTermsSnapshot },
    quantity: 200,
    unitPrice: 5,
    totalAmount: 1000,
    currency: 'USDT',
    computedNetProfit: 400,
    status: 'confirmed',
    createdByUserId: 'demo-user-1',
    createdAt: '2026-03-12T10:00:00Z',
    updatedAt: '2026-03-12T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'outgoing',
    merchantId: 'MRC-DEMO0001',
    merchantName: 'Al Jazeera Exchange',
    buyerId: 'BUY-004',
    buyerName: 'Fatima Noor',
    merchantAgreementId: demoAgreements[0].id,
    agreementTemplateId: demoTemplates[0].id,
    agreementType: 'profit_share',
    agreementSnapshot: { ...demoAgreements[0].resolvedTermsSnapshot },
    quantity: 75,
    unitPrice: 15,
    totalAmount: 1125,
    currency: 'USDT',
    computedNetProfit: 225,
    status: 'draft',
    createdByUserId: 'demo-user-1',
    createdAt: '2026-03-13T10:00:00Z',
    updatedAt: '2026-03-13T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'incoming',
    merchantId: 'MRC-DEMO0002',
    merchantName: 'Gulf Star Trading',
    buyerId: 'BUY-005',
    buyerName: 'Youssef Mansour',
    merchantAgreementId: demoAgreements[1].id,
    agreementTemplateId: demoTemplates[1].id,
    agreementType: 'fixed_margin',
    agreementSnapshot: { ...demoAgreements[1].resolvedTermsSnapshot },
    quantity: 100,
    unitPrice: 8,
    totalAmount: 800,
    currency: 'USDT',
    computedNetProfit: 200,
    status: 'confirmed',
    createdByUserId: 'demo-user-2',
    createdAt: '2026-03-14T10:00:00Z',
    updatedAt: '2026-03-14T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'outgoing',
    merchantId: 'MRC-DEMO0001',
    merchantName: 'Al Jazeera Exchange',
    buyerId: 'BUY-006',
    buyerName: 'Layla Ibrahim',
    merchantAgreementId: demoAgreements[0].id,
    agreementTemplateId: demoTemplates[0].id,
    agreementType: 'profit_share',
    agreementSnapshot: { ...demoAgreements[0].resolvedTermsSnapshot },
    quantity: 300,
    unitPrice: 12,
    totalAmount: 3600,
    currency: 'USDT',
    computedNetProfit: 720,
    status: 'cancelled',
    createdByUserId: 'demo-user-1',
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-03-16T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'incoming',
    merchantId: 'MRC-DEMO0001',
    merchantName: 'Al Jazeera Exchange',
    buyerId: 'BUY-007',
    buyerName: 'Karim Farouk',
    merchantAgreementId: demoAgreements[0].id,
    agreementTemplateId: demoTemplates[0].id,
    agreementType: 'profit_share',
    agreementSnapshot: { ...demoAgreements[0].resolvedTermsSnapshot },
    quantity: 150,
    unitPrice: 10,
    totalAmount: 1500,
    currency: 'USDT',
    computedNetProfit: 300,
    status: 'confirmed',
    createdByUserId: 'demo-user-3',
    createdAt: '2026-03-17T10:00:00Z',
    updatedAt: '2026-03-17T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'outgoing',
    merchantId: 'MRC-DEMO0002',
    merchantName: 'Gulf Star Trading',
    buyerId: 'BUY-008',
    buyerName: 'Nadia Salim',
    merchantAgreementId: demoAgreements[1].id,
    agreementTemplateId: demoTemplates[1].id,
    agreementType: 'fixed_margin',
    agreementSnapshot: { ...demoAgreements[1].resolvedTermsSnapshot },
    quantity: 50,
    unitPrice: 25,
    totalAmount: 1250,
    currency: 'USDT',
    computedNetProfit: 100,
    status: 'draft',
    createdByUserId: 'demo-user-1',
    createdAt: '2026-03-18T10:00:00Z',
    updatedAt: '2026-03-18T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'outgoing',
    merchantId: 'MRC-DEMO0001',
    merchantName: 'Al Jazeera Exchange',
    buyerId: 'BUY-009',
    buyerName: 'Tariq Bin Saeed',
    merchantAgreementId: demoAgreements[0].id,
    agreementTemplateId: demoTemplates[0].id,
    agreementType: 'profit_share',
    agreementSnapshot: { ...demoAgreements[0].resolvedTermsSnapshot },
    quantity: 500,
    unitPrice: 10,
    totalAmount: 5000,
    currency: 'USDT',
    computedNetProfit: 1000,
    status: 'confirmed',
    createdByUserId: 'demo-user-1',
    createdAt: '2026-03-19T10:00:00Z',
    updatedAt: '2026-03-19T10:00:00Z',
  },
  {
    id: createId('ORD'),
    direction: 'incoming',
    merchantId: 'MRC-DEMO0002',
    merchantName: 'Gulf Star Trading',
    buyerId: 'BUY-010',
    buyerName: 'Aisha Mohammed',
    merchantAgreementId: demoAgreements[1].id,
    agreementTemplateId: demoTemplates[1].id,
    agreementType: 'fixed_margin',
    agreementSnapshot: { ...demoAgreements[1].resolvedTermsSnapshot },
    quantity: 80,
    unitPrice: 15,
    totalAmount: 1200,
    currency: 'USDT',
    computedNetProfit: 160,
    status: 'confirmed',
    createdByUserId: 'demo-user-3',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-03-20T10:00:00Z',
  },
];
